# https://luppeng.wordpress.com/2020/02/28/install-and-start-postgresql-on-alpine-linux/


FROM node:18.16.0-alpine

RUN apk -U upgrade
RUN apk update
RUN apk add postgresql


COPY client /client/
COPY server /server/
COPY setup-script.sql /
COPY runStack.sh /

# IMPORTANT!
# DO NOT AUTO-EXPOSE PORTS !!
# Frontend
EXPOSE 3000
# EXPOSE 3001
# Backend
EXPOSE 5000 

RUN mkdir /run/postgresql
RUN chown postgres:postgres /run/postgresql/
USER postgres
RUN cd
RUN pwd
RUN mkdir /var/lib/postgresql/data
RUN chmod 0700 /var/lib/postgresql/data
RUN initdb -D /var/lib/postgresql/data
RUN echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
RUN echo "listen_addresses='*'" >> /var/lib/postgresql/data/postgresql.conf

RUN pg_ctl start -D /var/lib/postgresql/data && psql -c "\i /setup-script.sql" -U postgres


USER root
WORKDIR /client
RUN npm install -g @angular/cli
RUN echo N | ng analytics off
RUN ng build

WORKDIR /server
RUN npm remove bcrypt
RUN npm install bcrypt
RUN npm install bcryptjs
RUN npm install --global lite-server

CMD /runStack.sh

